"""add_story_descriptions_table

Revision ID: 2d9199b81b11
Revises: 92485a568833
Create Date: 2026-02-12 17:31:21.864256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2d9199b81b11'
down_revision: Union[str, None] = '92485a568833'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_descriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('story_id', sa.Uuid(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('acceptance_criteria', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_descriptions_id'), 'story_descriptions', ['id'], unique=False)
    op.create_index(op.f('ix_story_descriptions_story_id'), 'story_descriptions', ['story_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_story_descriptions_story_id'), table_name='story_descriptions')
    op.drop_index(op.f('ix_story_descriptions_id'), table_name='story_descriptions')
    op.drop_table('story_descriptions')
    # ### end Alembic commands ###
